import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { AlertTriangle, ArrowUpRight, AudioLines, BookMarked, CheckCircle2, ChevronDown, CircleDot, FileCheck2, FileSignature, FolderOpen, Lightbulb, MessageSquareText, UserRound } from "lucide-react"

import { AudioUploadForm } from "@/components/dashboard/audio-upload-form"
import { CaptureForm } from "@/components/dashboard/capture-form"
import { IdeaCompass } from "@/components/studio/idea-compass"
import { SectionHeading } from "@/components/studio/section-heading"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { readLeadPipeline, type LeadPipeline } from "@/lib/isa/lead-pipeline"
import { readOperationalPanel, type OperationalPanel } from "@/lib/isa/operational-panel"

const sectionMeta = {
  projetos: ["Projetos", "Movimento com contexto.", "Objetivos, tarefas e bloqueios lidos da fonte operacional do Studio."],
  clientes: ["Clientes", "Relações com memória.", "Histórico, documentos, alertas e próximo movimento de cada relação."],
  comercial: ["Comercial", "Valor precisa de contorno.", "Uma visão inicial das conversas, propostas e definições necessárias para transformar trabalho em receita."],
  captacao: ["Captação", "Sinal não é proposta.", "Indicações, pesquisa pública e próximos passos organizados antes de qualquer convite comercial."],
  repertorio: ["Repertório", "Referência não é decoração.", "O acervo visual e intelectual do Studio organizado como matéria de pesquisa, contraste e decisão."],
  decisoes: ["Decisões", "Escolher também é proteger.", "O que depende da founder, o que já está confirmado e o que não deve virar compromisso por acidente."],
  inteligencia: ["Memória e inteligência", "Capturar. Relacionar. Discernir.", "Uma entrada única para registrar contexto sem transformar automaticamente toda ideia em tarefa."],
  bussola: ["Bússola", "O que tem força agora?", "Possibilidades preservadas, com uma leitura visual de recorrência, conexão, foco e evidência."],
  sistema: ["Sistema", "A operação por trás do Studio.", "Agentes, skills, processos, playbooks e conexões organizados como infraestrutura interna."],
} as const

type SectionKey = keyof typeof sectionMeta
const labelClass = "text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-kobold"

export function generateStaticParams() {
  return Object.keys(sectionMeta).map((section) => ({ section }))
}

export async function generateMetadata({ params }: { params: Promise<{ section: string }> }): Promise<Metadata> {
  const { section } = await params
  const meta = sectionMeta[section as SectionKey]
  return { title: meta?.[0] ?? "Studio OS" }
}

function Projects({ panel }: { panel: OperationalPanel }) {
  return <div className="mt-8 grid gap-4 xl:grid-cols-2">{panel.projects.map((project) => <article key={project.name} className="overflow-hidden rounded-2xl border border-surface-300 bg-white"><div className="border-b border-surface-200 p-6"><div className="flex items-start justify-between gap-3"><h2 className="font-sans text-xl font-medium">{project.name}</h2><Badge variant="outline">{project.status}</Badge></div><p className="mt-4 text-sm leading-6 text-surface-600">{project.objective}</p></div><div className="space-y-5 p-6"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-kobold">Contexto</p><p className="mt-2 text-sm leading-6 text-surface-600">{project.context || "Contexto resumido ainda não registrado."}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-kobold">Próximas ações</p><div className="mt-2 space-y-2">{project.tasks.length ? project.tasks.map((task) => <p key={task} className="flex gap-2 rounded-xl bg-surface-100 p-3 text-xs leading-5"><CircleDot className="mt-0.5 size-3.5 shrink-0 text-brand-kobold" />{task}</p>) : <p className="text-xs text-surface-500">Nenhuma ação aberta registrada.</p>}</div></div><div className="rounded-xl border border-brand-sahara/40 bg-brand-arena/30 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-brand-cotta">Bloqueio</p><p className="mt-2 text-xs leading-5">{project.blocker}</p></div></div></article>)}</div>
}

function Clients({ panel }: { panel: OperationalPanel }) {
  const records = [[FileSignature, "Propostas"], [FileCheck2, "Contratos"], [FolderOpen, "Briefings"], [MessageSquareText, "Conversas"]] as const
  return <div className="mt-10 grid gap-6 xl:grid-cols-2">{panel.clients.map((client) => <article key={client.id} className="min-h-72 rounded-[1.75rem] border border-surface-300 bg-white p-7 shadow-[0_14px_42px_rgba(20,26,28,0.04)] sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className={labelClass}>Relação</p><h2 className="mt-3 font-sans text-2xl font-medium leading-tight">{client.name}</h2><p className="mt-2 text-sm leading-6 text-surface-500">{client.relationship}</p></div><Badge variant="outline">{client.status}</Badge></div><div className="mt-10 border-t border-surface-200 pt-5"><p className={labelClass}>Próximo movimento</p><p className="mt-2 max-w-xl text-sm font-medium leading-6">{client.next}</p></div><details className="group mt-7 border-t border-surface-200 pt-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-xs font-semibold"><span>Ver contexto e registros</span><ChevronDown className="size-4 text-brand-kobold transition-transform group-open:rotate-180" /></summary><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{records.map(([Icon, label]) => { const value = label === "Propostas" ? client.proposals : label === "Contratos" ? client.contracts : label === "Briefings" ? client.briefings : client.conversations; return <div key={label} className="rounded-xl bg-surface-100 p-3"><Icon className="size-3.5 text-brand-kobold" /><p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.12em]">{label}</p><p className="mt-1 text-[11px] leading-4 text-surface-500">{value}</p></div>})}</div><div className="mt-5 grid gap-4 border-t border-surface-200 pt-5 sm:grid-cols-[0.8fr_1.2fr]"><div><p className={labelClass}>Fonte</p><p className="mt-2 text-xs leading-5 text-surface-600">{client.source}</p></div>{client.alert ? <p className="flex gap-2 rounded-xl bg-brand-arena/35 p-3 text-xs leading-5"><AlertTriangle className="mt-0.5 size-3.5 shrink-0 text-brand-cotta" />{client.alert}</p> : <p className="text-xs leading-5 text-surface-500">Nenhum alerta adicional registrado.</p>}</div></details></article>)}</div>
}

function Commercial({ panel }: { panel: OperationalPanel }) {
  const stages = [
    ["Escuta", panel.clients.filter((client) => /descoberta|conversa|diagnóstico/i.test(client.status)).length, "Relações ainda formando contexto"],
    ["Definição", panel.clients.filter((client) => /proposta|escopo|formalização/i.test(`${client.status} ${client.next}`)).length, "Escopo, valor ou contrato em decisão"],
    ["Ativo", panel.clients.filter((client) => /ativo|andamento|execução/i.test(client.status)).length, "Trabalhos com movimento registrado"],
  ] as const
  return <div className="mt-8"><div className="grid gap-3 md:grid-cols-3">{stages.map(([label,value,note], index) => <article key={label} className={`rounded-2xl border p-6 ${index === 1 ? "border-brand-bleu/40 bg-brand-antar/45" : "border-surface-300 bg-white"}`}><span className="font-mono text-4xl">{value}</span><h2 className="mt-10 font-sans text-lg font-medium">{label}</h2><p className="mt-2 text-xs text-surface-500">{note}</p></article>)}</div><section className="mt-8 rounded-2xl border border-surface-300 bg-white"><div className="border-b border-surface-200 p-6"><p className={labelClass}>Fila de definição comercial</p><h2 className="mt-2 font-sans text-2xl font-medium">O que precisa ganhar contorno</h2></div><div className="divide-y divide-surface-200">{panel.clients.slice(0, 8).map((client) => <article key={client.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_1.4fr_auto] sm:items-center"><div><p className="font-medium">{client.name}</p><p className="mt-1 text-xs text-surface-500">{client.status}</p></div><p className="text-xs leading-5 text-surface-600">{client.next}</p><Badge variant="outline">A confirmar</Badge></article>)}</div></section></div>
}

function Captacao({ pipeline }: { pipeline: LeadPipeline }) {
  const activeIndex = pipeline.lead ? pipeline.stages.findIndex((stage) => stage.id === pipeline.lead?.state) : -1

  return <div className="mt-8 space-y-6">
    <section className="rounded-[1.75rem] border border-brand-bleu/30 bg-brand-antar/25 p-7 sm:p-8">
      <p className={labelClass}>Automação com revisão humana</p>
      <h2 className="mt-3 max-w-3xl font-sans text-2xl font-medium">A rotina organiza contexto, pesquisa e rascunhos. O Studio continua escolhendo quando — e se — uma conversa avança.</h2>
    </section>

    {pipeline.lead ? <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><article className="rounded-[1.75rem] border border-surface-950 bg-surface-950 p-7 text-white sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-brand-atmos">Lead em foco</p><h2 className="mt-3 font-sans text-2xl font-medium leading-tight">{pipeline.lead.title}</h2></div><Badge className="border-brand-atmos/30 bg-brand-atmos/10 text-brand-atmos">{pipeline.lead.state}</Badge></div><p className="mt-5 text-sm leading-6 text-surface-300">{pipeline.lead.origin}</p><div className="mt-8 border-t border-surface-800 pt-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-surface-500">Fatos registrados</p><ul className="mt-4 space-y-3">{pipeline.lead.facts.map((fact) => <li key={fact} className="flex gap-3 text-sm leading-5 text-surface-200"><CircleDot className="mt-1 size-3.5 shrink-0 text-brand-atmos" />{fact}</li>)}</ul></div></article><article className="rounded-[1.75rem] border border-surface-300 bg-white p-7 sm:p-8"><p className={labelClass}>Próximo movimento</p><h2 className="mt-3 font-sans text-2xl font-medium">Antes da pesquisa</h2><p className="mt-3 text-sm leading-6 text-surface-600">O lead ainda não tem identificação pública inequívoca. Por isso, o sistema não pesquisa nem sugere proposta.</p><ol className="mt-7 space-y-3">{pipeline.lead.nextSteps.map((step, index) => <li key={step} className="grid grid-cols-[24px_1fr] gap-3 text-sm leading-5"><span className="font-mono text-brand-kobold">0{index + 1}</span><span>{step}</span></li>)}</ol></article></section> : <section className="rounded-[1.75rem] border border-dashed border-surface-300 bg-white p-8 text-center"><p className={labelClass}>{pipeline.isDemo ? "Modo demonstrativo" : "Sem lead aberto"}</p><h2 className="mt-3 font-sans text-2xl font-medium">Os detalhes reais aparecem apenas no ambiente local.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-surface-600">O Preview preserva a privacidade. Ao registrar um lead localmente, esta área passa a mostrar o estado e o próximo movimento.</p></section>}

    <section className="rounded-[1.75rem] border border-surface-300 bg-white p-7 sm:p-8"><div className="max-w-2xl"><p className={labelClass}>Fluxo de direção</p><h2 className="mt-3 font-sans text-2xl font-medium">Do sinal ao encaminhamento</h2><p className="mt-3 text-sm leading-6 text-surface-600">Cada etapa só abre quando há contexto suficiente. As ações automáticas preparam o trabalho; as ações humanas mantêm relação, consentimento e decisão.</p></div><div className="mt-8 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{pipeline.stages.map((stage, index) => { const isCurrent = index === activeIndex; const isComplete = activeIndex > index; return <article key={stage.id} className={`min-h-56 rounded-2xl border p-5 ${isCurrent ? "border-brand-bleu bg-brand-antar/45" : isComplete ? "border-brand-midori/40 bg-brand-midori/10" : "border-surface-200 bg-surface-100/60"}`}><div className="flex items-start justify-between gap-3"><span className="font-mono text-[10px] text-brand-kobold">0{index + 1}</span>{isCurrent ? <Badge variant="outline">Agora</Badge> : isComplete ? <Badge variant="outline">Concluído</Badge> : null}</div><h3 className="mt-7 font-sans text-lg font-medium">{stage.label}</h3><div className="mt-5 space-y-4 border-t border-surface-300/70 pt-4"><div><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-surface-500">Sistema</p><p className="mt-1 text-xs leading-5 text-surface-600">{stage.automation}</p></div><div><p className="font-mono text-[9px] uppercase tracking-[0.15em] text-surface-500">Gleide</p><p className="mt-1 text-xs leading-5 text-surface-600">{stage.humanAction}</p></div></div></article>})}</div></section>
  </div>
}

function Repertoire() {
  const collections = [
    ["Curadoria visual", "15 + 1 pastas", "Padrões, tensões, arquétipos e contraprovas do repertório pessoal.", "Acervo interno · curadoria visual v2"],
    ["Direção de negócio", "7 módulos", "Tese, mercados, público, problemas, valor, oferta e direção estratégica.", "/docs/direcao-negocio/README.md"],
    ["Método Design Invisível", "28 prompts", "Pesquisa e direção de marca do fundamento à aplicação.", "/diretrizes/research"],
    ["Memória de projetos", "Acervo vivo", "Dossiês, conversas, aprendizados e decisões associados aos clientes.", "/docs/clientes/README.md"],
  ]
  const directionReferences = [{
    name: "Matt Gray",
    type: "Empreendedor criativo · nomadismo digital",
    status: "A confirmar",
    source: "matthgray_capturainstagram.png · Drive / 00_IDENTIDADE-STUDIO",
    observation: "Uma sequência extensa de publicações combina cenas ao ar livre, deslocamento, presença corporal, frases curtas e bastidores de trabalho e rotina.",
    possibleLearning: "Uma filosofia de vida pode ser comunicada por repetição de cenas, princípios e experiências — não apenas por explicações técnicas.",
    connection: "Investigar como posicionamento autoral, experiência e conteúdo podem formar um campo coerente para o diagnóstico do Studio.",
    question: "O que me inspira aqui: o modo de viver, o modo de trabalhar, o modo de comunicar ou a combinação dos três?",
  }]
  return <div className="mt-8 space-y-10">
    <div className="grid gap-3 sm:grid-cols-3">
      {[['01', 'Referência inicial', 'Matt Gray · registro-piloto'], ['04', 'Campos de leitura', 'origem · sinal · princípio · teste'], ['00', 'Decisões fechadas', 'tudo ainda passa pela sua escolha']].map(([value, title, note]) => <article key={title} className="rounded-2xl border border-surface-300 bg-white p-5"><p className="font-mono text-3xl font-medium">{value}</p><p className="mt-5 text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-surface-500">{note}</p></article>)}
    </div>

    <section className="overflow-hidden rounded-[1.75rem] border border-surface-950 bg-surface-950 text-white">
      <div className="grid gap-8 p-7 sm:p-9 lg:grid-cols-[1fr_0.8fr] lg:items-end">
        <div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-brand-atmos">Biblioteca de direção</p><h2 className="mt-4 max-w-2xl font-sans text-3xl font-medium leading-tight">Referências que ajudam a pensar melhor — sem virar cópia.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-surface-300">Aqui entram pessoas, práticas e ideias que podem ampliar sua metodologia. Cada registro precisa preservar a fonte, nomear o sinal observado e mostrar qual pergunta ou experimento ele abre.</p></div>
        <div className="rounded-2xl border border-surface-800 bg-surface-900/70 p-5"><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-brand-atmos">Como usar</p><div className="mt-5 space-y-4">{[[UserRound, 'Pessoa', 'quem carrega a referência'], [Lightbulb, 'Princípio', 'o que pode ser traduzido'], [BookMarked, 'Teste', 'onde verificar se faz sentido']].map(([Icon, title, body]) => { const CurrentIcon = Icon as typeof UserRound; return <div key={title as string} className="flex gap-3"><CurrentIcon className="mt-0.5 size-4 shrink-0 text-brand-atmos" /><p className="text-xs leading-5 text-surface-300"><strong className="block text-white">{title as string}</strong>{body as string}</p></div> })}</div></div>
      </div>
    </section>

    <section><div className="mb-5 flex items-end justify-between"><div><p className={labelClass}>Referências em leitura</p><h2 className="mt-2 font-sans text-2xl font-medium">Pessoas e princípios</h2></div><p className="hidden text-xs text-surface-500 sm:block">Fonte original preservada no Drive</p></div><div className="space-y-4">{directionReferences.map((reference) => <article key={reference.name} className="rounded-[1.75rem] border border-surface-300 bg-white p-7 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-brand-antar px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.14em] text-brand-kobold">{reference.status}</span><span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-surface-500">{reference.type}</span></div><h3 className="mt-4 font-sans text-3xl font-medium">{reference.name}</h3><p className="mt-2 text-xs text-surface-500">{reference.source}</p></div><p className="max-w-xs rounded-xl bg-surface-100 p-4 text-xs leading-5 text-surface-600">A ficha começa na observação e só avança quando você reconhece o que deseja levar para o Studio.</p></div><div className="mt-8 grid gap-4 border-t border-surface-200 pt-6 md:grid-cols-2"><div><p className={labelClass}>Observação</p><p className="mt-2 text-sm leading-6 text-surface-600">{reference.observation}</p></div><div><p className={labelClass}>Aprendizado possível</p><p className="mt-2 text-sm leading-6 text-surface-600">{reference.possibleLearning}</p></div><div><p className={labelClass}>Conexão com o Studio</p><p className="mt-2 text-sm leading-6 text-surface-600">{reference.connection}</p></div><div className="rounded-xl border border-brand-sahara/50 bg-brand-arena/30 p-4"><p className={`${labelClass} text-brand-cotta`}>Pergunta de validação</p><p className="mt-2 text-sm font-medium leading-6">{reference.question}</p></div></div></article>)}</div></section>

    <section className="grid gap-4 md:grid-cols-3">{[["Pessoas", "empreendedores, mentores e autores que ampliam seu campo de visão"], ["Práticas", "rituais, modelos de negócio e modos de trabalhar que merecem investigação"], ["Contrastes", "referências bonitas ou fortes que ajudam a descobrir o que não é seu"]].map(([title, description], index) => <article key={title} className="rounded-2xl border border-surface-300 bg-white p-6"><span className="font-mono text-[10px] text-brand-kobold">0{index + 1}</span><h3 className="mt-8 font-sans text-xl font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-surface-600">{description}</p></article>)}</section>

    <section><div className="mb-5"><p className={labelClass}>Acervos já existentes</p><h2 className="mt-2 font-sans text-2xl font-medium">Da inspiração à pesquisa aplicada</h2></div><div className="grid gap-4 md:grid-cols-2">{collections.map(([title,count,description,source], index) => <article key={title} className={`relative min-h-72 overflow-hidden rounded-[1.75rem] border p-7 ${index === 0 ? "border-surface-950 bg-surface-950 text-white" : "border-surface-300 bg-white"}`}><span className="font-mono text-[10px] uppercase tracking-[0.18em] opacity-55">Acervo 0{index + 1} · {count}</span><div className="absolute bottom-7 left-7 right-7"><h2 className="font-sans text-2xl font-medium">{title}</h2><p className="mt-3 text-sm leading-6 opacity-65">{description}</p><p className="mt-5 truncate font-mono text-[9px] opacity-45">{source}</p></div></article>)}</div></section>
  </div>
}

function System() {
  const areas = [
    ["Agentes", "Papéis de trabalho", "Quem escuta, estrutura, revisa ou executa dentro da operação."],
    ["Skills", "Capacidades reutilizáveis", "Instruções especializadas para direção, curadoria e tarefas recorrentes."],
    ["Processos e playbooks", "Como o trabalho acontece", "Passos, critérios e entregáveis que tornam uma boa prática repetível."],
    ["Scripts e conexões", "Infraestrutura com limite", "Automações e serviços só entram quando economizam tempo sem expor contexto indevidamente."],
  ]
  return <div className="mt-10 space-y-8"><section className="rounded-[1.75rem] border border-brand-bleu/30 bg-brand-antar/25 p-7 sm:p-8"><p className={labelClass}>Organização interna</p><h2 className="mt-3 max-w-2xl font-sans text-2xl font-medium">O Sistema é a casa da operação, não uma nova oferta.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-surface-600">Aqui ficam os recursos que ajudam o Studio a trabalhar com consistência. A experiência do cliente recebe apenas o que for selecionado e aprovado para ela.</p></section><div className="grid gap-6 md:grid-cols-2">{areas.map(([title, eyebrow, description], index) => <article key={title} className={`min-h-64 rounded-[1.75rem] border p-7 sm:p-8 ${index === 0 ? "border-surface-950 bg-surface-950 text-white" : "border-surface-300 bg-white"}`}><p className="font-mono text-[10px] uppercase tracking-[0.18em] opacity-55">0{index + 1} · {eyebrow}</p><div className="mt-16"><h2 className="font-sans text-2xl font-medium">{title}</h2><p className="mt-3 max-w-sm text-sm leading-6 opacity-70">{description}</p></div></article>)}</div><section className="rounded-[1.75rem] border border-surface-300 bg-white p-7 sm:p-8"><p className={labelClass}>Agora no Studio</p><div className="mt-5 grid gap-5 lg:grid-cols-4"><article><h2 className="font-medium">ISA Direction</h2><p className="mt-2 text-xs leading-5 text-surface-600">Escuta, foco, força das ideias e recibos de atualização.</p></article><article><h2 className="font-medium">Captação para direção</h2><p className="mt-2 text-xs leading-5 text-surface-600">Classifica indicações e preserva o momento certo de pesquisar ou convidar.</p></article><article><h2 className="font-medium">Pesquisa para direção</h2><p className="mt-2 text-xs leading-5 text-surface-600">Transforma fontes públicas e setoriais em perguntas verificáveis.</p></article><article><h2 className="font-medium">Curadoria de repertório visual</h2><p className="mt-2 text-xs leading-5 text-surface-600">Transforma referências em hipóteses rastreáveis, sem fechar a identidade por conta própria.</p></article></div></section></div>
}

function Decisions({ panel }: { panel: OperationalPanel }) {
  const confirmed = panel.clarity.confirmed.filter((item) => !/\bisa\b/i.test(item))
  const pending = panel.decisions.concat(panel.clarity.pending).filter((item) => !/\bisa\b/i.test(item))
  return <div className="mt-8 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-surface-300 bg-white"><div className="border-b border-surface-200 p-6"><p className={`${labelClass} text-brand-midori`}>Direção confirmada</p><h2 className="mt-2 font-sans text-2xl font-medium">O que já orienta o Studio</h2></div><div className="divide-y divide-surface-200">{confirmed.map((item) => <p key={item} className="flex gap-3 p-5 text-sm leading-6"><CheckCircle2 className="mt-1 size-4 shrink-0 text-brand-midori" />{item}</p>)}</div></section><section className="rounded-2xl border border-brand-sahara/50 bg-brand-arena/30"><div className="border-b border-brand-sahara/40 p-6"><p className={`${labelClass} text-brand-cotta`}>Decisão da founder</p><h2 className="mt-2 font-sans text-2xl font-medium">O que permanece aberto</h2></div><div className="divide-y divide-brand-sahara/30">{pending.slice(0, 10).map((item) => <p key={item} className="flex gap-3 p-5 text-sm leading-6"><CircleDot className="mt-1 size-4 shrink-0 text-brand-cotta" />{item}</p>)}</div></section></div>
}

function Intelligence({ panel }: { panel: OperationalPanel }) {
  return <div className="mt-8 grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><Card className="bg-white"><CardHeader><CardTitle className="font-sans text-xl">Registrar contexto</CardTitle><CardDescription>Ideia, conversa, prazo, pessoa, decisão ou bloqueio.</CardDescription></CardHeader><CardContent><CaptureForm /></CardContent></Card><Card className="bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-sans text-xl"><AudioLines className="size-5 text-brand-kobold" /> Captura por áudio</CardTitle><CardDescription>Use o celular quando escrever interromper o pensamento.</CardDescription></CardHeader><CardContent><AudioUploadForm /></CardContent></Card><section className="rounded-2xl border border-brand-bleu/30 bg-brand-antar/25 p-6 xl:col-span-2"><p className={labelClass}>Recibo das conversas</p><h2 className="mt-2 font-sans text-2xl font-medium">O que a ISA atualizou</h2><p className="mt-2 text-sm leading-6 text-surface-600">Cada conversa que muda o estado do Studio deixa um rastro: registrado, refletido nesta plataforma ou aguardando uma ação concreta.</p><div className="mt-5 divide-y divide-brand-bleu/15 rounded-xl bg-white">{panel.isaUpdates.slice(-5).reverse().map((update) => <article key={`${update.date}-${update.change}`} className="grid gap-3 p-4 sm:grid-cols-[100px_1fr_auto]"><div><p className="font-mono text-[10px] text-brand-kobold">{update.date}</p><p className="mt-1 text-[10px] text-surface-500">{update.origin}</p></div><div><p className="text-sm leading-5">{update.change}</p><p className="mt-1 text-xs text-surface-500">Conferir: {update.location}</p></div><span className="h-fit rounded-full bg-surface-100 px-2.5 py-1 text-[10px] font-semibold text-surface-700">{update.status}</span></article>)}</div></section><section className="rounded-2xl border border-surface-300 bg-white p-6 xl:col-span-2"><p className={labelClass}>Protocolo de discernimento</p><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Capturar","O registro preserva o contexto sem prometer execução."],["Relacionar","A informação é conectada a projetos, pessoas e decisões existentes."],["Confirmar","Mudanças de prioridade, prazo ou compromisso continuam dependendo de validação humana."]].map(([title,description], index) => <article key={title} className="rounded-xl bg-surface-100 p-5"><span className="font-mono text-[9px] text-brand-kobold">0{index + 1}</span><h2 className="mt-8 font-sans text-lg font-medium">{title}</h2><p className="mt-2 text-xs leading-5 text-surface-600">{description}</p></article>)}</div><p className="mt-5 font-mono text-[9px] uppercase tracking-[0.14em] text-surface-500">Fonte operacional consolidada em {panel.lastConsolidation}</p></section></div>
}

export default async function OsSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params
  if (!(section in sectionMeta)) notFound()
  const key = section as SectionKey
  const [eyebrow, title, description] = sectionMeta[key]
  const [panel, pipeline] = await Promise.all([readOperationalPanel(), readLeadPipeline()])
  return <div className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><SectionHeading eyebrow={eyebrow} title={title} description={description} />{key === "projetos" ? <Projects panel={panel} /> : key === "clientes" ? <Clients panel={panel} /> : key === "comercial" ? <Commercial panel={panel} /> : key === "captacao" ? <Captacao pipeline={pipeline} /> : key === "repertorio" ? <Repertoire /> : key === "decisoes" ? <Decisions panel={panel} /> : key === "bussola" ? <IdeaCompass /> : key === "sistema" ? <System /> : <Intelligence panel={panel} />}<footer className="mt-14 flex items-center justify-between border-t border-surface-300 pt-5"><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-surface-500">Studio OS · Alpha 0.1</p><Link href="/os" className="inline-flex items-center gap-2 text-xs font-semibold">Voltar à visão geral <ArrowUpRight className="size-3.5" /></Link></footer></div>
}
