import Link from "next/link"
import type { LucideIcon } from "lucide-react"
import { ArrowLeft, ArrowRight } from "lucide-react"

import { PublicFooter } from "@/components/studio/public-footer"
import { PublicHeader } from "@/components/studio/public-header"

export type AreaItem = { number: string; title: string; description: string; status: string; icon: LucideIcon }

export function PublicAreaPage({ eyebrow, title, lead, statement, items, accent = "blue" }: { eyebrow: string; title: string; lead: string; statement: string; items: AreaItem[]; accent?: "blue" | "sand" | "pink" }) {
  const accents = { blue: "bg-brand-antar/55", sand: "bg-brand-arena/55", pink: "bg-brand-calla/40" }
  return <div className="min-h-screen bg-surface-white text-surface-950"><PublicHeader /><main><section className={`border-b border-surface-300 ${accents[accent]}`}><div className="mx-auto max-w-[var(--content-width)] px-5 py-20 sm:px-8 lg:py-28"><Link href="/" className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-surface-600"><ArrowLeft className="size-3.5" /> Ecossistema</Link><div className="mt-16 grid gap-10 lg:grid-cols-[1.2fr_0.8fr] lg:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-brand-kobold">{eyebrow}</p><h1 className="mt-5 font-sans text-5xl font-medium leading-[0.9] sm:text-7xl xl:text-8xl">{title}</h1></div><p className="max-w-xl text-base leading-7 text-surface-700">{lead}</p></div></div></section><section className="mx-auto max-w-[var(--content-width)] px-5 py-20 sm:px-8 lg:py-28"><p className="max-w-5xl font-sans text-3xl font-medium leading-[1.05] sm:text-5xl">{statement}</p><div className="mt-16 grid gap-px overflow-hidden rounded-[1.75rem] border border-surface-300 bg-surface-300 md:grid-cols-2">{items.map((item) => { const Icon = item.icon; return <article key={item.number} className="min-h-72 bg-white p-7 sm:p-9"><div className="flex items-start justify-between"><span className="font-mono text-[10px] text-surface-500">{item.number}</span><Icon className="size-5 text-brand-kobold" /></div><div className="mt-20"><div className="flex items-center gap-2"><span className="size-1.5 rounded-full bg-brand-midori" /><span className="font-mono text-[9px] uppercase tracking-[0.15em] text-surface-500">{item.status}</span></div><h2 className="mt-4 font-sans text-2xl font-medium">{item.title}</h2><p className="mt-3 max-w-md text-sm leading-6 text-surface-600">{item.description}</p></div></article>})}</div><div className="mt-16 flex flex-col items-start justify-between gap-6 border-t border-surface-300 pt-8 sm:flex-row sm:items-center"><p className="max-w-xl text-sm leading-6 text-surface-600">Esta área nasce como estrutura evolutiva. As funcionalidades serão ativadas à medida que forem validadas em uso real.</p><Link href="/os" className="inline-flex items-center gap-2 rounded-full bg-surface-950 px-5 py-3 text-xs font-semibold text-white">Conhecer o núcleo operacional <ArrowRight className="size-3.5" /></Link></div></section></main><PublicFooter /></div>
}
